name: Deploy

on:
  push:
    tags: ['*']

jobs:
  deploy:
    name: Build & push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7

      - uses: docker/setup-qemu-action@v4

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/tasztalos69/jszp:${{ github.ref_name }}
            ghcr.io/tasztalos69/jszp:latest
